site_name: wandb_preempt
site_url: https://https://readthedocs.org/projects/wandb_preempt/
repo_url: https://github.com/f-dangel/wandb_preempt/
repo_name: f-dangel/wandb_preempt
site_author: Felix Dangel, Scott Lowe
watch:
  - wandb_preempt
nav:
    - Getting Started: index.md
    - API Documentation: api.md
    - Walkthrough Example: walkthrough.md
    - Developer Notes: develop.md
theme:
    name: material
    features:
        - content.code.copy
copyright: Copyright &copy; 2024 Felix Dangel, Scott Lowe
markdown_extensions:
    - pymdownx.arithmatex: # LaTeX math
          generic: true
    - pymdownx.highlight: # code highlighting
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite # code highlighting
    - pymdownx.snippets # code highlighting
    - pymdownx.superfences # code highlighting
    - pymdownx.blocks.details # fold-able content
    - footnotes
plugins:
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                      show_root_heading: true
                      show_source: true
                      show_bases: true
                      show_signature_annotations: true
                      separate_signature: true
                      docstring_section_style: list
                      merge_init_into_class: true
    - search
extra_javascript:
    - javascripts/mathjax.js # LaTeX math
    - https://polyfill.io/v3/polyfill.min.js?features=es6 # LaTeX math
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # LaTeX math
